
-- Generated by ORDS REST Data Services 25.4.2.r0502119
-- Schema: USU_REGMED  Date: Sun Mar 22 01:58:53 2026 
--
        
DECLARE
  l_roles     OWA.VC_ARR;
  l_modules   OWA.VC_ARR;
  l_patterns  OWA.VC_ARR;

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'usu_regmed',
      p_auto_rest_auth      => TRUE);

  ORDS.DEFINE_MODULE(
      p_module_name    => 'modulo_registro',
      p_base_path      => '/registro/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => 'API para registro de eventos diarios');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'modulo_registro',
      p_pattern        => 'alimentacion/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'modulo_registro',
      p_pattern        => 'alimentacion/',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
    v_id NUMBER;
BEGIN
    -- Los valores :cantidad_ml, :metodo y :notas provendrán directamente
    -- de las claves del JSON enviado en el cuerpo de la petición.
    
    INSERT INTO registro_alimentacion (cantidad_ml, metodo, notas)
    VALUES (:cantidad_ml, NVL(:metodo, ''Mamadera''), :notas)
    RETURNING id_alimentacion INTO v_id;
    
    -- Configurar la respuesta de éxito
    :status_code := 201;
    -- Opcional: devolver el ID insertado
    -- HTP.P(''{"status":"success", "id_insertado": '' || v_id || ''}'');
EXCEPTION
    WHEN OTHERS THEN
        :status_code := 400;
        -- En un entorno productivo, manejaríamos el log del error
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'modulo_registro',
      p_pattern        => 'panales/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'modulo_registro',
      p_pattern        => 'panales/',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'BEGIN
    INSERT INTO registro_panales (tipo, notas)
    VALUES (:tipo, :notas);
    
    :status_code := 201;
EXCEPTION
    WHEN OTHERS THEN
        :status_code := 400;
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'modulo_registro',
      p_pattern        => 'medicacion/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'modulo_registro',
      p_pattern        => 'medicacion/',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
    v_id_med NUMBER;
    v_unidad_medida VARCHAR2(10);
    v_dosis NUMBER;
BEGIN
    -- Buscamos el ID del medicamento basado en el nombre que envía la IA
    BEGIN
        SELECT id_medicamento, UNIDAD_MEDIDA, DOSIS_ESPERADA 
        INTO v_id_med, v_unidad_medida, v_dosis
        FROM cat_medicamentos 
        WHERE UPPER(nombre) LIKE ''%'' || UPPER(:nombre_medicamento) || ''%'' 
        AND estado = ''ACTIVO'' 
        FETCH FIRST 1 ROWS ONLY; -- Previene error si hay nombres similares
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            -- Si la IA entendió mal el nombre o no existe, devolvemos error
            :status_code := 404;
            RETURN;
    END;

    --TODO: Por defecto debe trar unidad de medida del catalogo de medicamentos,
    -- a menos que en la instrucción venga una diferente

    INSERT INTO registro_medicacion (id_medicamento, dosis, unidad_medida, notas)
    VALUES (v_id_med, NVL(:dosis,v_dosis), v_unidad_medida, :notas);
    
    :status_code := 201' || ';
EXCEPTION
    WHEN OTHERS THEN
        :status_code := 400;
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'modulo_registro',
      p_pattern        => 'dialisis/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'modulo_registro',
      p_pattern        => 'dialisis/',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
  l_cantidad_infusiones parametros_dialisis.cantidad_infusiones%type;
  l_volumen_infusion_ml parametros_dialisis.volumen_infusion_ml%type;
  l_tiempo_perman_infusion_min parametros_dialisis.tiempo_perman_infusion_min%type;
  l_tiempo_total_tratam_horas parametros_dialisis.tiempo_total_tratam_horas%type;
  l_tiene_ultima_infusion parametros_dialisis.tiene_ultima_infusion%type;
  l_volumen_ultima_infusion_ml parametros_dialisis.volumen_ultima_infusion_ml%type;
BEGIN
    BEGIN
        SELECT cantidad_infusiones, volumen_infusion_ml, tiempo_perman_infusion_min, tiempo_total_tratam_horas, tiene_ultima_infusion, volumen_ultima_infusion_ml
        INTO l_cantidad_infusiones, l_volumen_infusion_ml, l_tiempo_perman_infusion_min, l_tiempo_total_tratam_horas, l_tiene_ultima_infusion, l_volumen_ultima_infusion_ml
        FROM PARAMETROS_DIALISIS
       WHERE fecha_registro = (SELECT MAX(fecha_registro) FROM parametros_dialisis);
    END;
    INSERT INTO registro_dialisis (
        ultrafi' || 'ltracion_ml, drenaje_inicial_ml, cantidad_infusiones, volumen_infusion_ml, 
        tiempo_perman_infusion_min, TIEMPO_TOTAL_TRATAM_HORAS, tiene_ultima_infusion, volumen_ultima_infusion_ml, notas
    ) VALUES (
        :ultrafiltracion_ml, :drenaje_inicial_ml, l_cantidad_infusiones, l_volumen_infusion_ml, 
        l_tiempo_perman_infusion_min, l_tiempo_total_tratam_horas, l_tiene_ultima_infusion, l_volumen_ultima_infusion_ml, :notas
    );
    
    :status_code := 201;
EXCEPTION
    WHEN OTHERS THEN
        :status_code := 400;
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'modulo_registro',
      p_pattern        => 'citas/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'modulo_registro',
      p_pattern        => 'citas/',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'BEGIN
INSERT INTO bitacora_citas_medicas (
        especialista, peso_kg, talla_cm, presion_arterial, indicaciones
    ) VALUES (
        :especialista, :peso_kg, :talla_cm, :presion_arterial, :indicaciones
    );
    
    :status_code := 201;
EXCEPTION
    WHEN OTHERS THEN
        :status_code := 400;
END;');


COMMIT;

END;