
-- Generated by ORDS REST Data Services 25.4.2.r0502119
-- Schema: USU_REGMED  Date: Sun Mar 22 02:32:52 2026 
--
        
DECLARE
  l_roles     OWA.VC_ARR;
  l_modules   OWA.VC_ARR;
  l_patterns  OWA.VC_ARR;

BEGIN
   -- Warning: privileges do not protect modules during
   -- OAuth Client standalone export.
    
  ORDS.CREATE_ROLE(
      p_role_name=> 'rol_bot_registro');
  l_roles(1) := 'rol_bot_registro';
  l_patterns(1) := 'registro/*';

  ORDS.DEFINE_PRIVILEGE(
      p_privilege_name => 'privilegio_registro',
      p_roles          => l_roles,
      p_patterns       => l_patterns,
      p_modules        => l_modules,
      p_label          => 'Privilegio API Registro',
      p_description    => 'Protege los endpoints de ingreso de datos diarios',
      p_comments       => NULL); 

  l_roles.DELETE;
  l_modules.DELETE;
  l_patterns.DELETE;


  ORDS_SECURITY.IMPORT_CLIENT(
      p_name             => 'cliente_node_bot',
      p_client_id        => 'Hlex7eQ-QW6CaucUgqImjg..',
      p_grant_type       => 'client_credentials',
      p_owner            => 'USU_REGMED',
      p_description      => 'Cliente para el Middleware en Node.js',
      p_origins_allowed  => NULL,
      p_redirect_uri     => NULL,
      p_support_email    => 'jeanomobono@gmail.com',
      p_support_uri      => NULL,
      p_token_duration   => NULL,
      p_refresh_duration => NULL,
      p_code_duration    => NULL,
      p_privilege_names  => 'privilegio_registro');

   ORDS_SECURITY.GRANT_CLIENT_ROLE(
      p_client_name     => 'cliente_node_bot',
      p_role_name => 'rol_bot_registro');

COMMIT;

END;