CREATE TABLE registro_alimentacion (
   id_alimentacion NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   fecha_hora      TIMESTAMP DEFAULT current_timestamp NOT NULL,
   cantidad_ml     NUMBER NOT NULL,
   metodo          VARCHAR2(50) DEFAULT 'Mamadera',
   notas           VARCHAR2(500)
);

CREATE TABLE registro_panales (
   id_panal   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   fecha_hora TIMESTAMP DEFAULT current_timestamp NOT NULL,
   tipo       VARCHAR2(50) NOT NULL, -- Ej: 'Orina', 'Deposición', 'Mixto', 'Seco'
   notas      VARCHAR2(500)
);

CREATE TABLE cat_medicamentos (
   id_medicamento NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   nombre         VARCHAR2(100) NOT NULL,
   nombre_comercial VARCHAR2(100),
   dosis_esperada NUMBER, -- Útil para validaciones
   unidad_medida  VARCHAR2(10), -- ml, capsulas, sobres, etc.
   estado         VARCHAR2(10) DEFAULT 'ACTIVO'
);

CREATE TABLE registro_medicacion (
   id_registro_med NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   id_medicamento  NUMBER
      REFERENCES cat_medicamentos ( id_medicamento ),
   fecha_hora      TIMESTAMP DEFAULT current_timestamp NOT NULL,
   dosis           NUMBER NOT NULL,
   unidad_medida   VARCHAR2(10) NOT NULL,
   notas           VARCHAR2(500)
);

CREATE TABLE parametros_dialisis (
   id_parametro                    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   fecha_registro                  DATE DEFAULT trunc(sysdate) NOT NULL,
   cantidad_infusiones             NUMBER NOT NULL,
   volumen_infusion_ml             NUMBER NOT NULL,
   tiempo_perman_infusion_min NUMBER NOT NULL, -- En minutos
   tiempo_total_tratam_horas  NUMBER NOT NULL,
   tiene_ultima_infusion           VARCHAR2(1) DEFAULT 'N' CHECK ( tiene_ultima_infusion IN ( 'S',
                                                                                    'N' ) ),
   volumen_ultima_infusion_ml      NUMBER,
   notas                           VARCHAR2(1000)
);

CREATE TABLE registro_dialisis (
   id_dialisis                     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   fecha_registro                  DATE DEFAULT trunc(sysdate) NOT NULL, -- Fecha de la mañana en que se revisa
    
    -- Resultado
   ultrafiltracion_ml              NUMBER NOT NULL,
   drenaje_inicial_ml              NUMBER NOT NULL,
    
    -- Parámetros de la máquina de esa noche
   cantidad_infusiones             NUMBER NOT NULL,
   volumen_infusion_ml             NUMBER NOT NULL,
   tiempo_perman_infusion_min NUMBER NOT NULL, -- En minutos
   tiempo_total_tratam_horas  NUMBER NOT NULL,
   tiene_ultima_infusion           VARCHAR2(1) DEFAULT 'N' CHECK ( tiene_ultima_infusion IN ( 'S',
                                                                                    'N' ) ),
   volumen_ultima_infusion_ml      NUMBER,
   notas                           VARCHAR2(1000)
);

CREATE TABLE bitacora_citas_medicas (
   id_cita          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   fecha_cita       DATE DEFAULT trunc(sysdate) NOT NULL,
   especialista     VARCHAR2(100), -- Ej: 'Nefrología', 'Pediatría'
   peso_kg          NUMBER,
   talla_cm         NUMBER,
   presion_arterial VARCHAR2(20), -- Ej: '100/60'
   indicaciones     VARCHAR2(1000)
);

-- Tabla Maestra: Guarda la fecha y el documento físico
CREATE TABLE registro_laboratorios (
   id_laboratorio NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   fecha_estudio  DATE NOT NULL,
   archivo_pdf    BLOB,
   nombre_archivo VARCHAR2(255),
   mimetype       VARCHAR2(100),
   notas          VARCHAR2(500)
);

-- Tabla Detalle: Guarda los valores individuales para poder graficarlos
CREATE TABLE detalle_laboratorio (
   id_detalle     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   id_laboratorio NUMBER
      REFERENCES registro_laboratorios ( id_laboratorio )
         ON DELETE CASCADE,
   marcador       VARCHAR2(50) NOT NULL, -- Ej: 'Creatinina', 'Potasio', 'Hemoglobina'
   valor          NUMBER NOT NULL,
   unidad         VARCHAR2(20)           -- Ej: 'mg/dL', 'mEq/L'
);